# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: genqrcode.proto for package 'genqrcode'

require 'grpc'
require 'genqrcode_pb'

module Genqrcode
  module GenQrCodeService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'genqrcode.GenQrCodeService'

      rpc :Generate, ::Genqrcode::RequestCode, ::Genqrcode::ResponseCode
    end

    Stub = Service.rpc_stub_class
  end
end
